import glob
import os
import re

_FAVICON_RE = re.compile(r'<link rel="icon" href="([^"]*)">')


def _expand_favicon(m: re.Match) -> str:
    # Derive the relative base path from the matched href (e.g. '' or '../').
    href = m.group(1)
    base = href[: href.index("assets/")]
    return (
        f'<link rel="icon" href="{base}assets/favicon.svg" type="image/svg+xml">\n'
        f'      <link rel="icon" href="{base}assets/favicon.png" sizes="48x48">\n'
        f'      <link rel="icon" href="{base}assets/favicon.ico">'
    )


def on_post_page(output, **kwargs):
    # MkDocs Material hardcodes display=fallback; swap renders text immediately (better LCP).
    output = output.replace("display=fallback", "display=swap")
    # Replace Material's single favicon link with SVG → PNG → ICO fallback chain.
    return _FAVICON_RE.sub(_expand_favicon, output)


def on_post_build(config, **kwargs):
    # 404.html is generated by Material in on_post_build before our hook runs, so
    # on_post_page never fires for it and the privacy plugin downloads a fallback-CSS copy.
    # Patch all downloaded font CSS files so every page gets font-display:swap.
    pattern = os.path.join(
        config["site_dir"], "assets", "external", "fonts.googleapis.com", "*.css"
    )
    for path in glob.glob(pattern):
        with open(path, encoding="utf-8") as f:
            css = f.read()
        patched = css.replace("font-display: fallback", "font-display: swap")
        if patched != css:
            with open(path, "w", encoding="utf-8") as f:
                f.write(patched)
