import os
import glob


def on_post_page(output, **kwargs):
    # MkDocs Material hardcodes display=fallback; swap renders text immediately (better LCP).
    return output.replace("display=fallback", "display=swap")


def on_post_build(config, **kwargs):
    # 404.html is generated by Material in on_post_build before our hook runs, so
    # on_post_page never fires for it and the privacy plugin downloads a fallback-CSS copy.
    # Patch all downloaded font CSS files so every page gets font-display:swap.
    pattern = os.path.join(
        config["site_dir"], "assets", "external", "fonts.googleapis.com", "*.css"
    )
    for path in glob.glob(pattern):
        with open(path, encoding="utf-8") as f:
            css = f.read()
        patched = css.replace("font-display: fallback", "font-display: swap")
        if patched != css:
            with open(path, "w", encoding="utf-8") as f:
                f.write(patched)